### ISSUE TITLE
Optional unlimited thinking time

### ISSUE THREAD

**Issue by lotodore** [pokerth/pokerth#24]
**Reporter: neugrek**
Optional unlimited thinking time to facilitate for example on-off games in the office or pausing for drinks in a LAN game (or pause option?)

**Comment by clydegale** [comment]
Is there a reason this is only working for network games? We want to play on our self hosted server (i.e. "Internet Game") but a few of the people have kids and might need to leave the table for an unknown amount of time.

So what I'm asking is:
Can you implement the unlimited player timeout also for "Internet Games"? (i.e. self-hosted server)

**Comment by q4z1** [comment]
> but a few of the people have kids and might need to leave the table for an unknown amount of time.

Direct answer? Not now. I do put it on a list now.

Regards.
