### ISSUE TITLE
Default Server Address for Android game is incorrect

### ISSUE THREAD

**Issue by markusbrand** [pokerth/pokerth#289]
If you try to start an internet game with the android app (version 1.1.1), it says incorrect server address.

**Comment by lotodore** [comment]
I do not have this issue. Please try to reset your settings to default.

**Comment by theodr** [comment]
Same problem here. I think it is related to lollipop version of Android, since I started having this problem when I updated my android from kit-kat to lollipop.

**Comment by BuZZ-dEE** [comment]
I also have this problem on lollipop.

**Comment by shepguessed** [comment]
same problem here

**Comment by MiaWallace71** [comment]
Since an update to lollipop I do have this problem too

**Comment by gonello** [comment]
Try unchecking "Use IPv6" in Configure PokerTH / Internet Game / Server tab.

**Comment by TheodoreT** [comment]
the "Use IPv6" option is already unchecked plus if I try to change any option in the Configure PokerTH settings it gives me the message 

>>THE LOG FILE DIRECTORY DOESN'T EXIST.
>>PLEASE SELECT AN VALID DIRECTORY!

so my guess for both problems is that due to some file system changes in lollipop the app cannot find the proper path to the needed files

**Comment by MiaWallace71** [comment]
I have an ASUS Fonepad 7 ( FE375CXG ) and the same problem as TheodoreT (logfile doesn't exist...)

**Comment by lotodore** [comment]
I have looked through the code and it seems that on Lollipop the method call getenv("HOME") returns NULL (see configfile.cpp line 121), meaning that no home directory is set for the app. I can see no other case where the log path would be initially empty.

This is quite some problem, as the code in this file needs to be portable for Windows, Linux and Mac OS... I have no idea why the HOME environment variable not set on Lollipop, and could not find any information about this on google.

As I have no Lollipop device available, I cannot test any possible fix. I'll try to provide a "theoretical" patch, however...

**Comment by q4z1** [comment]
should be solved now with PokerTH-1.1.1-Android20151208.apk release
