### ISSUE TITLE
ranking after fast game shut down

### ISSUE THREAD

**Issue by TheArtist1** [pokerth/pokerth#292]
hi,

after a regular ranked 10 players' game, I won the last heads-up and left the game a very short time after I saw the yellow "winner" word on my avatar (like 0,3 second after), but the game got registered on my account as a top2 and the log file is now corrupted.

That is to say, I believe the game doesn't register well the ranking and the log if you close the game right after you win (or lose?) the last hand (or any hand?).

Do you experience the same thing ? Are you aware of that ?

**Comment by lotodore** [comment]
Hi,

I'm sorry that you lost the game in this state, but there is a delay between winning the last hand and winning the game. And if you are offline in this state, it may count as not winning. Generally, this is on purpose, as no one in offline state should win the game (there is a specific check for that). I understand that your situation was special, but you would have needed to stay online only a few more seconds.

Concerning the corrupt log file: This depends on how you terminated PokerTH. If you regularly terminated it, this should not happen. If you kind of "killed" the PokerTH application, for example by shutting down Windows and forcing quit of PokerTH, then this may happen.

**Comment by lotodore** [comment]
As there has been no more feedback, I will close this issue now. If you encounter a corrupt log file when regularly terminating PokerTH, please create a new issue.
