### ISSUE TITLE
Issue in score calculation

### ISSUE THREAD

**Issue by Bartelemy** [pokerth/pokerth#301]
Hi, My account name is Barthélémy.
In this season there is a bug in score calculation. The system adds sometimes 7th places, which I have never played.
In the game history these 7th places does not registered, but they are taken to count the 'Games played' value. Thats why I have a very poor score - system calculate my average with 97 instead of  80 really played games. State: 31-Jan-2016 10:15h GMT.

The system calculates a wrong average of 7.19 - the right value should be 8.50.
Can an admin please fix this issue and correct my score?

**Comment by thomasboehm** [comment]
There are other players who randomly get 1st places added. There are a few threads about this in the pokerth forum, but not a single reply even acknowledging the problem.

Here are a few examples

http://www.poker-heroes.com/profile.html?user=Bigwill
9 wins, but 23 wins counted for ranking

http://www.poker-heroes.com/profile.html?user=Harry1
5 wins, but 31 wins counted for ranking

http://www.poker-heroes.com/profile.html?user=sota
18 wins, but 36 wins counted for ranking

http://www.poker-heroes.com/profile.html?user=TheWonderful
14 wins, but 30 wins counted for ranking

http://www.poker-heroes.com/profile.html?user=Muller-SPb
3 wins, but 28 wins counted for ranking

http://www.poker-heroes.com/profile.html?user=jorj
25 wins, but 51 wins counted for ranking

http://www.poker-heroes.com/profile.html?user=italo55
15 wins, but 35 wins counted for ranking

http://www.poker-heroes.com/profile.html?user=Odessa
4 wins, but 14 wins counted for ranking

**Comment by lotodore** [comment]
Please report this to poker-heroes. I'm sorry, but we cannot fix this issue in the pokerth source code, so this is not the right place to report it.
