### ISSUE TITLE
Players deliberately preventing start of play

### ISSUE THREAD

**Issue by MilkmanUK** [pokerth/pokerth#304]
There are some players that deliberately jump out of games just before they start and then jump back in again within a microsecond, doing this constantly to prevent a game starting.
I was unable to join any 5sec open game on the 16th of Feb for over 15 minutes due to one particular player doing this constantly.
This continued on the 17th of February to the frustration and annoyance of several players who just wanted to get on and play.
My suggestion would be a 5 second delay between a player leaving a game and being able to re-enter the same game. This would give plenty of time for another player to take the place and the game to proceed as normal.

**Comment by q4z1** [comment]
solved - player can only enter/leave the same open game 6 times.
