### ISSUE TITLE
Can login on website, can't login on the Linux app

### ISSUE THREAD

**Issue by giacecco** [pokerth/pokerth#308]
Hi, it's all in the title. I originally thought the issue was my very complicated password, but I tried dumbing it down to 8 letters and digits only, and I'm still out. I am using the 1.1.1 Linux version distributed through the Fedora repositories, running on Fedora 23. Any suggestion?

**Comment by Ralgert** [comment]
confirm by win xp pro 32

**Comment by doitux** [comment]
This should be fixed in 1.1.2 since there is a brand new registration system.
