### ISSUE TITLE
Ignore feature only works after restart

### ISSUE THREAD

**Issue by doitux** [pokerth/pokerth#320]
https://pokerth.net/community/forum/2-general-feedback/13320-two-bugs?limitstart=0#35607

Maybe a OS independent issue? Needs more testing ...

**Comment by q4z1** [comment]
Worked for me without re-login - even during a game.

**Comment by doitux** [comment]
If you ignore a player ingame it works in the chat. But when you come back into the lobby the lobby chat doesnt ignore him. After a restart it works. So it seems there is an update of the chat-tools needed to re-read the ignore list when come back in the lobby after a game.

**Comment by doitux** [comment]
fixed in upcoming version 1.1.2
