### ISSUE TITLE
Double usernames

### ISSUE THREAD

**Issue by bugmenot2** [pokerth/pokerth#322]
See Harry and harry or Sheldor and sheldor. The database shouldn't be case-sensitive.

**Comment by q4z1** [comment]
I dont see a "real" reason to change it - as it is only a matter of taste. For me "Sheldor" and "sheldor" are completely different nicknames.

**Comment by bugmenot2** [comment]
Only Linux nerds see them as different names. ;-) No offense, I myself am using it. But lets be real, the average user perceives the names as the same - because they have been trained over the years: usernames are case-INsensitive. BTW, even on the ranking gametable (when you click on a username during a game) both names are listed instead of only the actual playing one so at least that has to change.

If this will be kept as it is I recommend all users to create both accounts to forestall ID theft.

**Comment by q4z1** [comment]
Thx for the hint - showing both "users" in game-table will be fixed then.
