### ISSUE TITLE
possible LAST_INSERT_ID() bug

### ISSUE THREAD

**Issue by q4z1** [pokerth/pokerth#324]
* regularely 20 entries in game_has_player table have the game id = 0
... game report won't work with that. 

ToDo:

change server code: src/dbofficial/asyncdbcreategame.cpp:61 using something more reliable than LAST_INSERT_ID() which seems to fail from time to time.
Make a query like "SELECT idgame FROM game ORDER BY idgame DESC LIMIT 0,1
and +1 the value.

**Comment by CyberBLN** [comment]
In my opinion the game ID get lost in DBIdManager. Adding logging there should help to find the real reason.

**Comment by q4z1** [comment]
> In my opinion the game ID get lost in DBIdManager. Adding logging there should help to find the real reason.

Thank you for the hint. albmed already mentionend that there follows an `if gameid == 0` check in the above file/lline - so the origin of the error really has to be somewhere else ;)

**Comment by q4z1** [comment]
Seems to be an encoding issue with game-table name - I changed field definition to utf8mb4 now.
