### ISSUE TITLE
Muted for saying the word 'sucker' even though it's poker jargon

### ISSUE THREAD

**Issue by louwers** [pokerth/pokerth#329]
I propose the word 'suck' is removed from the bad words list. As of now, the word 'sucker' cannot be used in chat, even though it is a technical poker term. 

'sucker' can also be added to the exceptions list, but I'd argue for removing it altogether ('[suckout](http://dictionary.pokerzone.com/Suck+Out)', 'that sucks' etc.)

**Comment by q4z1** [comment]
suck is still in - but I added an exception for sucker, that sucks and suckout.

**Comment by louwers** [comment]
![screenshot_2017-04-23_00-39-48](https://cloud.githubusercontent.com/assets/649392/25308817/8d42b99e-27bd-11e7-88c2-68680057dbb6.png)
Why not get rid of the whole censoring system altogether? It's ineffective.

**Comment by q4z1** [comment]
Thx for reporting it - player got banned.

**Comment by louwers** [comment]
Oh I didn't know rules were enforced. 

Good to know, thanks.
