### ISSUE TITLE
Minimum rank table requirement

### ISSUE THREAD

**Issue by louwers** [pokerth/pokerth#331]
There is a problem with players not taking the game seriously. These players, sometimes dubbed 'all-in idiots' or 'bingo players' just push all-in all the time, without any sound poker strategy (as is almost always evident from their ranks).

Since this these players add so much randomness to the game, the existence of these players is a big detriment to the enjoyment of many (more serious) players.

To counter this problem I would like to propose a feature that would allow table operators to set a minimum rank to join that table. I am interested to know if other players also would like to see this feature, and the technical feasibility of it.

**Comment by q4z1** [comment]
Please be patient. Ideas do already exist - time is what's needed.
