### ISSUE TITLE
Screen Freeze of a Different Sort

### ISSUE THREAD

**Issue by BankshotMurphy** [pokerth/pokerth#337]
Middle of a game, at the end of a hand.  Everything freezes except the "start" button in the low, right corner.  Clicking the start button wipes out the game being played and starts a new game.

![poker stall](https://user-images.githubusercontent.com/33769378/32975888-bf4050b0-cbd1-11e7-90ff-a0d5125f8ab2.JPG)
![poker stall2](https://user-images.githubusercontent.com/33769378/32975889-bf5b0b12-cbd1-11e7-94b5-196ef42e6f8d.JPG)

**Comment by q4z1** [comment]
Can you try it with the 1.1.2 Version?
https://sourceforge.net/projects/pokerth/files/pokerth/1.1.2/

**Comment by BankshotMurphy** [comment]
> Can you try it with the 1.1.2 Version and check if it is happening there too?
https://sourceforge.net/projects/pokerth/files/pokerth/1.1.2/

Does it happen only in games with computer opponents?

>

**Comment by BankshotMurphy** [comment]
> Can you try it with the 1.1.2 Version and check if it is happening there too?
https://sourceforge.net/projects/pokerth/files/pokerth/1.1.2/
Does it happen only in games with computer 

Just downloaded v1.1.2 and will need a few days to play with it.

**Comment by BankshotMurphy** [comment]
After a few days of playing with v1.1.2, the game has not frozen again (yet?).  Possibly the new download was the fix.  If it resumes acting up, I will
