### ISSUE TITLE
Cannot build 1.1.2 on archLinux with protobuf 3.5

### ISSUE THREAD

**Issue by blacktav** [pokerth/pokerth#339]
qt4 0.4.2-3
boost 1.65.1-2
gcc 7.2.1-2
protobuf 3.5.0.1-1

In file included from src/third_party/protobuf/pokerth.pb.cc:5:0:
src/third_party/protobuf/pokerth.pb.h:17:2: error: #error This file was generated by an older version of protoc which is

full error reports attached
[comp.log](https://github.com/pokerth/pokerth/files/1609839/comp.log)

**Comment by q4z1** [comment]
You have to re-generate these files with your protoc version:

`protoc -I=/path/to/pokerth/ --cpp_out=/path/to/pokerth/src/third_party/protobuf/ /path/to/pokerth/pokerth.proto /path/to/pokerth/chatcleaner.proto`

**Comment by blacktav** [comment]
Thanks

This throws this error and I cannot figure how to correct pokerth.proto

[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: pokerth.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
pokerth.proto:706:26: Expected enum value or number range.

**Comment by blacktav** [comment]
Beg pardon, error should be at line 704 - I was trying to add 'syntax = "proto2";' at the top of the file to silence the warning

[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: pokerth.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
pokerth.proto:704:26: Expected enum value or number range.

**Comment by q4z1** [comment]
This is only a warning that can be ignored.

Did you try to compile again after re-generation with protoc?

**Comment by blacktav** [comment]
Yep, exactly the same error message(s)

in src/third_party/protobuf
chatcleaner.* have been regenerated but pokerth.pb.* have not

How can I get these regenerated?

**Comment by q4z1** [comment]
Weird.

Are you using stable branch or master branch?

You have to use stable branch! ...

**Comment by blacktav** [comment]
Ah right, there is a problem rebuilding with pokerth.proto

Using the proto command above on a revised pokerth.proto to silence the warning throws an error which can't be ignored it seems. 

pokerth.proto:706:26: Expected enum value or number range.

The errant section seems to be (from line 704 so 706 begins "reserved = 0;")

message ErrorMessage {
        enum ErrorReason {
                reserved = 0;
                initVersionNotSupported = 1;
                initServerFull = 2;
                initAuthFailure = 3;
                initPlayerNameInUse = 4;
                initInvalidPlayerName = 5;
                initServerMaintenance = 6;
                initBlocked = 7;
                avatarTooLarge = 8;
                invalidPacket = 9;
                invalidState = 10;
                kickedFromServer = 11;
                bannedFromServer = 12;
                blockedByServer = 13;
                sessionTimeout = 14;
        }
        required        ErrorReason             errorReason = 1;
}

**Comment by q4z1** [comment]
can you try to add the following in line 720:
`required	ErrorReason		errorReason = 1  [default = reserved] ;`

protobuf3 obviously made some changes with enums ...

**Comment by blacktav** [comment]
> can you try to add the following in line 720:

not sure if you meant adding a new line or editing the existing line; anyways no change either way, still getting 

pokerth.proto:706:26: Expected enum value or number range.

**Comment by q4z1** [comment]
Ok. For now I can only recommend using protobuf 2.x

We will have to take a deeper look - my Vbox has protobux 2.6.1 and it works there.

Just be patient a few days - thank you for reporting ;)

**Comment by blacktav** [comment]
I think "reserved" may be a reserved word now regardless of forcing proto2 syntax on

see section "Reserved fields"

https://developers.google.com/protocol-buffers/docs/proto

Have fun figuring that one out ;)

**Comment by q4z1** [comment]
Good point. As this "reserved = 0;" value does not seem to be used - just try to rename "reserved" to "custReserved" or kinda.
Maybe it works ...

**Comment by blacktav** [comment]
Yay, good call!

Doing that regenerated the proto files. The "reserved" field is referenced in src/net/common/netpacket.cpp (and maybe other places) so renaming it there too seemed a good plan.

Build was going fine till it hit the problem below which appears unrelated - is that an easy fix do you think? Do you need more info like a full log?

src/gui/qt/gametable/gametableimpl.cpp: In member function ‘void gameTableImpl::triggerVoteOnKick(int)’:
src/gui/qt/gametable/gametableimpl.cpp:3862:18: error: call of overloaded ‘advance(PlayerListIterator&, int&)’ is ambiguous
   advance(pos, id);
                  ^
In file included from /usr/include/c++/7.2.1/bits/stl_algobase.h:66:0,
                 from /usr/include/c++/7.2.1/algorithm:61,
                 from ../../../../include/qt4/QtCore/qglobal.h:68,
                 from ../../../../include/qt4/QtCore/qatomic.h:45,
                 from ../../../../include/qt4/QtCore/qvariant.h:45,
                 from ../../../../include/qt4/QtCore/QVariant:1,
                 from uics/ui_gametable.h:12,
                 from src/gui/qt/gametable/gametableimpl.h:38,
                 from src/gui/qt/gametable/gametableimpl.cpp:31:
/usr/include/c++/7.2.1/bits/stl_iterator_base_funcs.h:197:5: note: candidate: void std::advance(_InputIterator&, _Distance) [with _InputIterator = std::_List_iterator<boost::shared_ptr<PlayerInterface> >; _Distance = int]
     advance(_InputIterator& __i, _Distance __n)
     ^~~~~~~
In file included from /usr/include/boost/next_prior.hpp:25:0,
                 from /usr/include/boost/utility.hpp:19,
                 from /usr/include/boost/range/size.hpp:25,
                 from /usr/include/boost/range/functions.hpp:20,
                 from /usr/include/boost/range/iterator_range_core.hpp:38,
                 from /usr/include/boost/algorithm/string/replace.hpp:16,
                 from /usr/include/boost/date_time/date_facet.hpp:17,
                 from /usr/include/boost/date_time/gregorian/gregorian_io.hpp:16,
                 from /usr/include/boost/date_time/gregorian/gregorian.hpp:31,
                 from /usr/include/boost/date_time/posix_time/time_formatters.hpp:12,
                 from /usr/include/boost/date_time/posix_time/posix_time.hpp:24,
                 from src/third_party/boost/timers/portable/clock_device.hpp:18,
                 from src/third_party/boost/timers/portable.hpp:15,
                 from src/third_party/boost/timers.hpp:22,
                 from src/gui/qt/gametable/mytimeoutlabel.h:39,
                 from uics/ui_gametable.h:45,
                 from src/gui/qt/gametable/gametableimpl.h:38,
                 from src/gui/qt/gametable/gametableimpl.cpp:31:
/usr/include/boost/iterator/advance.hpp:68:9: note: candidate: constexpr void boost::iterators::advance_adl_barrier::advance(InputIterator&, Distance) [with InputIterator = std::_List_iterator<boost::shared_ptr<PlayerInterface> >; Distance = int]
         advance(InputIterator& it, Distance n)
         ^~~~~~~
make[1]: *** [Makefile.pokerth_game:1209: obj/gametableimpl.o] Error 1
make[1]: Leaving directory '/usr/src/pokerth/src/pokerth-1.1.2-rc'
make: *** [Makefile:142: sub-pokerth_game-pro-make_default-ordered] Error 2

**Comment by albmed** [comment]
Hi  blacktav, 

Just qualify the call to `advance` with `std` in `gametableimpl.cpp`. I mean: 

```
std::advance(pos, id); 
```

Regards, 
Albert.

**Comment by blacktav** [comment]
Hi Albert

Perfect! 
clean compile & install - thanks guys
[Albert: the syntax warning was obscuring the real error message]

Will these changes be making their way into source with a prompt new release?
If so I will wait for the new release before creating a distro package for AUR

Summary of changes: Edits
pokerth.proto:704: rename to "custReserved = 0;"
net/common/netpacket.cpp:252:  rename to "retVal = ErrorMessage::custReserved;"
src/gui/qt/gametable/gametableimpl.cpp:3862: change to "std::advance(pos, id);"

Rebuild protobuf:
protoc -I=/path/to/pokerth/ --cpp_out=/path/to/pokerth/src/third_party/protobuf/ /path/to/pokerth/pokerth.proto /path/to/pokerth/chatcleaner.proto

**Comment by albmed** [comment]
Hi blacktav,

Qualify `advance` with `std`, together with issue #338 will be added to `stable` branch as soon as we make enough tests to make sure everything works as expected. 

Regarding rename `reserved` variable to `custReserved` I don't see the need to do it. I usually compile `.proto` files using protobuf v3.X and I never had any problem with it. If you want to avoid the syntax warning just add 
```
syntax = "proto2";
```
as the first non-empty, non-comment line in .proto files 

Regards, 
Albert.

**Comment by q4z1** [comment]
@albmed we should also add the syntax line to proto files then maybe?

**Comment by albmed** [comment]
@q4z1, sure ;)

**Comment by blacktav** [comment]
@albmed the "reserved" variable name is in fact a keyword for protobuf v3 (since v3.0.0 in 2015); even if it passes now, it will eventually fail I would think and you will have to rename anyway (and/or there may be side-effects). In v3.5.0 the keyword could be added in enums (it was not before this) and presumably it is this version introduces the "problem"

**Comment by albmed** [comment]
Hi blacktav, 

You are right!! This variable must be renamed as you already did. 
Sorry for my suspicion, but I didn't expect that kind of changes in the middle of a major version (v3).  

Thanks a lot for reporting. We well correct as soon as possible. 

Regards, 
Albert.

**Comment by Enlik** [comment]
Renames in two places make it build. Thank you both!

**Comment by steils** [comment]
Looks like the bug is still here.
I need this patch to compile Pokerth: https://gitweb.gentoo.org/repo/gentoo.git/tree/games-board/pokerth/files/pokerth-1.1.2-protobuf.patch
My protobuf version is 3.11.4.

**Comment by steils** [comment]
Oh, I see. The above-mentioned PR is merged into 'stable' branch, but not into 'master'.

**Comment by andy5995** [comment]
@blacktav Manjaro user here... your [AUR package](https://aur.archlinux.org/packages/pokerth/) works well for me. Thanks.
