### ISSUE TITLE
How to suppress -isystem in Makefiles

### ISSUE THREAD

**Issue by blacktav** [pokerth/pokerth#340]
Hi

I am having a problem with gcc v7 that can barf with "-isystem /usr/include"

Do you know how I can suppress the isystem switch and just have -I/usr/include

Unfortunately I cannot reliably replicate the problem although when it does occur, editing the Makefiles to change "-isystem /usr/include" to be "-I/usr/include" permits the build to complete.

Since the Makefiles are created on the fly and I am trying to create an automated build, at a loss how to address this. 

distro: ArchLinux
qt5: 5.10
qmake: 3.1
gcc: 7.2.1
pokerth 1.1.2

g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -Wall -W -D_REENTRANT -DENABLE_IPV6 -DTIXML_USE_STL -DQT_NO_DEBUG -I. -I. -Isrc **-isystem /usr/include** -I/usr/lib/qt/mkspecs/linux-g++ -o obj/serverdbcallback.o src/db/common/serverdbcallback.cpp
In file included from /usr/include/c++/7.2.1/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7.2.1/bits/basic_string.h:6349,
                 from /usr/include/c++/7.2.1/string:52,
                 from src/db/dbdefs.h:36,
                 from src/db/serverdbcallback.h:36,
                 from src/db/common/serverdbcallback.cpp:32:
/usr/include/c++/7.2.1/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.pokerth_db:888: obj/serverdbcallback.o] Error 1
make[1]: Leaving directory '/home/drew/.cache/pacaur/pokerth/src/pokerth-1.1.2-rc'
make: *** [Makefile:74: sub-pokerth_db-pro-make_first-ordered] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by blacktav** [comment]
Sorry forgot this...

distro: ArchLinux
qmake: 5.10
gcc: 7.2.1
pokerth 1.1.2

**Comment by blacktav** [comment]
Oops
qmake:3.1, qt:5.10

**Comment by blacktav** [comment]
I believe I have a workaround:

Instead of doing something like this 
  `qmake CONFIG+="client" pokerth.pro`
add QMAKE_CFLAGS_ISYSTEM= so for example
   `qmake) QMAKE_CFLAGS_ISYSTEM= CONFIG+="client" pokerth.pro`
seems to work

Please see link below for a clue to a proper fix (first comment is relevant)
 https://bugreports.qt.io/browse/QTBUG-53367

**Comment by albmed** [comment]
Hi , 

First, as you can see in [wiki](https://github.com/pokerth/pokerth/wiki/Building-PokerTH-for-Linux) PokerTH has not been tested with gcc-7, yet. So, it can throw some errors (such as the problem with `advance` function). Anyway, thanks for testing... you are helping us :) 

Regarding your problem with `stdlib.h` is a known bug with QT (it is also explained in wiki). Just add `QMAKE_CFLAGS_ISYSTEM=""` when creating Makefiles with `qmake`. I mean: 

```
qmake CONFIG+="client" QMAKE_CFLAGS_ISYSTEM="" -spec linux-g++ pokerth.pro
```

Please, tell us if that works.

Kind regards,
Albert.

**Comment by albmed** [comment]
Exactly. It looks we answered at once xD 
In wiki, you can find any problem we faced when building PokerTH.  

Don't hesitate to ask for any other problem. Just remember, PokerTH has not been tested with gcc-7 and there could be some problems we didn't know about. We appreciate that you report any other problem. 

Thanks a lot. I close this issue.

Regards, 
Albert.

**Comment by blacktav** [comment]
@albmed I found the workaround independently and was just recording it as your comment came in - dammit, I didn't notice the wiki
yep, that seems to work OK

Thanks
