### ISSUE TITLE
pokerth patch from archlinux

### ISSUE THREAD

**Issue by itamarjp** [pokerth/pokerth#348]
please apply this patch from archlinux, 

it makes it build in new compilers.

https://aur.archlinux.org/packages/pokerth/

https://aur.archlinux.org/cgit/aur.git/tree/pokerth-1.1.2.patch?h=pokerth

**Comment by albmed** [comment]
Hi @itamarjp, thanks for your work. However these bugs have been already detected and noted in our [wiki](https://github.com/pokerth/pokerth/wiki). 

On the other hand, I also corrected them all in my own repository (https://github.com/albmed/pokerth/commit/678da490d4144d4a3199b2a0be371152dd48daef), but I didn't promoted to this official PokerTH repository, until we make sure these corrections work as expected. 

Kind regards, 
Albert.
