### ISSUE TITLE
Installation issue on Mac OS 10.13.6

### ISSUE THREAD

**Issue by b1t3s1z3** [pokerth/pokerth#353]
Hi folks,

Trying to install this program from source. I seem able to run the qmake command (no errors thrown), but when I run the "make" command I get a perplexing error...

`Colonial-One:pokerth trevor$ make
( test -e Makefile.pokerth_protocol || /usr/local/Cellar/qt/5.11.1/bin/qmake -o Makefile.pokerth_protocol /Users/trevor/Documents/GitHub/pokerth/pokerth_protocol.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.pokerth_protocol 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -fPIC -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.6 -Wall -W -DENABLE_IPV6 -DQT_NO_DEBUG -I. -I. -Isrc -I/Developer/SDKs/MacOSX10.6.sdk/usr/include/ -I/Library/Frameworks/SDL.framework/Headers -I/Library/Frameworks/SDL_mixer.framework/Headers -I/usr/local/include -I/anaconda3/mkspecs/macx-clang -o obj/pokerth.pb.o src/third_party/protobuf/pokerth.pb.cc
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
make[1]: *** [obj/pokerth.pb.o] Error 1
make: *** [sub-pokerth_protocol-pro-make_first-ordered] Error 2`

I'm sure the error is _not_ that my system requires OS X 10.7 or later, as I am running version OS 10.13.6. Am going to investigate this issue further, but any insight from you all would be greatly appreciated.

Thanks!

**Comment by q4z1** [comment]
Hi bitesize,

can you check your installed SDKs? make seems to look here `-Isrc -I/Developer/SDKs/MacOSX10.6.sdk/usr/include/`:
/Developer/SDKs/MacOSX10.6.sdk/usr/include/ - and if this folder is present, it might be the reason, why make complains about >=10.7. Version.

I also suggest using qt 5.9.x Version if possible, as qt >5.9.x has not been tested by now.

Kind regards.

**Comment by b1t3s1z3** [comment]
Hi q4z1,

Thanks for your reply. I was following the INSTALL text document from the pokerth source, but have no started over following the Building-PokerTH-for_MacOS article over in the wiki.

Everything seems good, up until the `make` command:

`Colonial-One:pokerth trevor$ make`
`...
...
...`
`... ... ...` (Output abbreviated so you can see the errors.)

`**In file included from /usr/local/include/boost/config/no_tr1/cmath.hpp:21:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: 
      no member named 'signbit' in the global namespace
using ::signbit;**
      ~~^
**/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: 
      no member named 'fpclassify' in the global namespace
using ::fpclassify;**
      ~~^
**/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:315:9: error: 
      no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;**
      ~~^
/usr/include/math.h:757:12: note: 'finite' declared here
extern int finite(double) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __M...
           ^
In file included from src/db/common/serverdbfactory.cpp:32:
In file included from src/db/serverdbfactory.h:36:
In file included from /usr/local/include/boost/asio.hpp:24:
In file included from /usr/local/include/boost/asio/basic_deadline_timer.hpp:28:
In file included from /usr/local/include/boost/asio/time_traits.hpp:23:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time_types.hpp:12:
In file included from /usr/local/include/boost/date_time/posix_time/ptime.hpp:12:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time_system.hpp:13:
In file included from /usr/local/include/boost/date_time/posix_time/posix_time_config.hpp:15:
In file included from /usr/local/include/boost/config/no_tr1/cmath.hpp:21:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:316:9: error: 
      no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:317:9: error: 
      no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error: 
      no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:7: error: 
      no member named 'isgreater' in the global namespace; did you mean
      '::std::greater'?
using ::isgreater;
      ^~
`

Some web searching gives me a few clues as to the source of these errors, but I would be curious to hear your unbiased thoughts on how to resolve this.

Thanks again,

+Trevor

**Comment by albmed** [comment]
Hi Trevor,

All these errors seems to be related with boost or c++ libraries. 

Perhaps there is an error hidden among the rest of output. 
Can you send us entire output or post it in pastebin.com and send us the link, please? 

Regards, 
Albert.

**Comment by albmed** [comment]
Hi Trevor, 

This looks to be a MacOS problem. and not a PokerTH issue. For what I saw in several posts (e.g.: https://stackoverflow.com/questions/22889822/errors-in-cstdint-no-member-named-xxx-in-global-namespace), the problem occurs when you install libraries under `/usr/local`. 

Sorry, but I think I can't help, because I never used a MacOS. 
Perhaps my colleague @q4z1 can give you a hand. I'll tell him. 

Regards, 
Albert

**Comment by q4z1** [comment]
Hi Trevor,

unfortunately I do not have a Mac or neither a working VM with Mac OS at the moment.

But I propably found a solution:
https://stackoverflow.com/questions/47018913/make-fails-on-mac

Please manually edit the Makefile(s) and use `clang++` instead of `gcc -x c++`.

Let us know if it works. ;)

Regards.

**Comment by b1t3s1z3** [comment]
Hi q4z1,

Thanks for your response, I suspect you are on to a solution here.

I am having trouble locating the "gcc -x c++" code in any of the Makefiles contained in my pokerth directory.

In my pokerth directory, I have three files that might be the Makefile you're talking about –
"Makefile"
"Makefile.pokerth_db"
and "Makefile.pokerth_protocol"

I have searched through these files, but cannot find the string in question. Any advice?

Also, my system does appear to be executing with clang++ rather than gcc -x c++, based on the first bit of output (highlighted here):
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/**clang++ -c -pipe -stdlib=libc++ -O2 -fPIC -std=gnu++11  -arch x86_64 -isysroot** /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.13 -Wall -W -DENABLE_IPV6 -DTIXML_USE_STL -DQT_NO_DEBUG -I. -I. -Isrc -I/usr/include -I/Developer/SDKs/MacOSX10.6.sdk/usr/include/ -I/Library/Frameworks/SDL.framework/Headers -I/Library/Frameworks/SDL_mixer.framework/Headers -I/usr/local/include -I/usr/local/Cellar/qt/5.11.1/mkspecs/macx-clang -o obj/serverdbfactory.o src/db/common/serverdbfactory.cpp
`

Do you agree?

+Trevor

**Comment by q4z1** [comment]
Hi Trevor,

if you don't mind - please post Makefile here.

I will be "near" a Mini-Mac on Fr-Sun - so I can also check it there. If I remember right, my last compiling errors during the try to build 1.1.2 for mac were the same. So I can make a check, too then.

Regards.

**Comment by b1t3s1z3** [comment]
Hi q4z1,

https://pastebin.com/embed_js/dR7kq1NT

I've pasted it to paste bin where it will persist for seven days. Let me know if you have any issues opening it.

Thanks.

**Comment by q4z1** [comment]
Got it - thx b1t3s1z3

**Comment by q4z1** [comment]
Ah yeah - nearly expected it ... can you @b1t3s1z3  provide Makefile.pokerth_game - the global Makefile doesn't directly call a compiler. Sorry for that.

**Comment by albmed** [comment]
Hi, 
I know nothing about MacOS, but if I'm not wrong compiler is defined by qmake in `mkspecs` directory under QT install path. 
Anyway C & C++ compilers can be overwritten using `QMAKE_CC` and `QMAKE_CXX` environment variables. For instance: 

    qmake CONFIG+="client c++11" QMAKE_CC="/usr/bin/gcc" QMAKE_CXX="/usr/bin/g++" -spec macx-g++  pokerth.pro

or 

    qmake CONFIG+="client c++11" QMAKE_CC="/usr/bin/clang" QMAKE_CXX="/usr/bin/clang++" -spec macx-clang  pokerth.pro

**Comment by b1t3s1z3** [comment]
> Ah yeah - nearly expected it ... can you @b1t3s1z3 provide Makefile.pokerth_game - the global Makefile doesn't directly call a compiler. Sorry for that.

Hi q4z1,

I don't seem to have a Makefile.pokerth_game file. I have Makefile, Makefile.pokerth_db, and Makefile.pokerth_protocol. 

+Trevor

**Comment by q4z1** [comment]
Hi Trevor,

I just checked in a linux system - and obviously the other Makefiles are generated during make Process.

Did you try both qmake commands from @albmed out?

I can imagine, that this will work.

Regards.

**Comment by b1t3s1z3** [comment]
Tried both qmake commands from @albmed, but no success. I get the same errors both times.

**Comment by q4z1** [comment]
@b1t3s1z3 I cannot help you without making my own test on a mac then - sorry :(
I will try to borrow a mac next weeks - hopefully before end of year.

Regards,

q4z1

**Comment by hffaust** [comment]
Did anyone ever figure this out? 😢

**Comment by hffaust** [comment]
I get this error after following the mac osx wiki install instructions:
`( test -e Makefile.pokerth_protocol || /usr/local/opt/qt/bin/qmake -o Makefile.pokerth_protocol /Users/hfaust/Documents/ClonedProjects/pokerth/pokerth_protocol.pro 'CONFIG+=client c++11' QMAKE_CC=/usr/bin/clang QMAKE_CXX=/usr/bin/clang++ -spec macx-clang ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.pokerth_protocol
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -fPIC -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6 -Wall -W -frtti -DENABLE_IPV6 -DQT_NO_DEBUG -I. -I. -Isrc -I/Developer/SDKs/MacOSX10.6.sdk/usr/include/ -I/Library/Frameworks/SDL.framework/Headers -I/Library/Frameworks/SDL_mixer.framework/Headers -I/usr/local/include -I/usr/local/Cellar/qt/5.13.0/mkspecs/macx-clang -o obj/pokerth.pb.o src/third_party/protobuf/pokerth.pb.cc
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
make[1]: *** [obj/pokerth.pb.o] Error 1
make: *** [sub-pokerth_protocol-pro-make_first-ordered] Error 2`

**Comment by q4z1** [comment]
@hffaust:

Your error is a common issue with different prototype versions. Just delete the files in `src/third_party/protobuf/` and re-create them:

https://developers.google.com/protocol-buffers/docs/cpptutorial

e.g.: protoc -I=$SRC_DIR --cpp_out=$DST_DIR $SRC_DIR/pokerth.pro
