### ISSUE TITLE
When building server, `make install` does nothing

### ISSUE THREAD

**Issue by urkud** [pokerth/pokerth#358]
The reason is that
https://github.com/pokerth/pokerth/blob/df59bf750f8ce000e600e45fb47cdc5d545c45cf/pokerth_server.pro#L292
mentions `pokerth_server` while `TARGET` is `bin/pokerth_server`, see
https://github.com/pokerth/pokerth/blob/df59bf750f8ce000e600e45fb47cdc5d545c45cf/pokerth_server.pro#L13

**Comment by albmed** [comment]
Hi @urkud
Unlike client, PokerTH server is not intended to be installed running ` make install`, because it must be run with full path command line. So, it's not advisable to put `pokerth_server` within `$PATH`
