### ISSUE TITLE
Test on ubuntu 16.04,18.04, and debian 8,it not work.

### ISSUE THREAD

**Issue by kokomoji** [pokerth/pokerth#359]
I follow wiki step,and  make release.
It always show:
src/core/common/crypthelper.cpp: In static member function 'static bool CryptHelper::AES128Encrypt(const unsigned char*, unsigned int, const string&, std::vector<unsigned char>&)':
src/core/common/crypthelper.cpp:294:18: error: aggregate 'EVP_CIPHER_CTX encryptCtx' has incomplete type and cannot be defined
   EVP_CIPHER_CTX encryptCtx;
                  ^
src/core/common/crypthelper.cpp: In static member function 'static bool CryptHelper::AES128Decrypt(const unsigned char*, unsigned int, const unsigned char*, unsigned int, std::__cxx11::string&)':
src/core/common/crypthelper.cpp:341:18: error: aggregate 'EVP_CIPHER_CTX decryptCtx' has incomplete type and cannot be defined
   EVP_CIPHER_CTX decryptCtx;
                  ^
make[2]: *** [obj/crypthelper.o] Error 1
make[1]: *** [release] Error 2
make: *** [sub-pokerth_lib-pro-release_ordered] Error 2
Can someone help me?

Thank you!

**Comment by albmed** [comment]
Hi @kokomoji, 

It looks you are trying to build PokerTH with OpenSSL version 1.1.X. This version has made opaque some structures from versions 1.0.X, which are used in PokerTH. `EVP_CIPHER_CTX` among them: https://www.openssl.org/news/openssl-1.1.0-notes.html

To make it build, you should use OpenSSL v1.0.X. In the future we'll try to adapt PokerTH to be built with new versions.

**Comment by kokomoji** [comment]
> Hi @kokomoji,
> 
> It looks you are trying to build PokerTH with OpenSSL version 1.1.X. This version has made opaque some structures from versions 1.0.X, which are used in PokerTH. `EVP_CIPHER_CTX` among them: https://www.openssl.org/news/openssl-1.1.0-notes.html
> 
> To make it build, you should use OpenSSL v1.0.X. In the future we'll try to adapt PokerTH to be built with new versions.

Hi, Thanks for your reply.
It seems the version of openssl  is 1.0.1f.
root@ubuntu:/opt/mingw/pokerth# openssl version
OpenSSL 1.0.1f 6 Jan 2014

**Comment by redlance72** [comment]
i have the same issue with OpenSSL 1.0.2g on Ubuntu16.04
has anyone found the solution?
thanx

**Comment by albmed** [comment]
Hi @redlance72 @kokomoji 

Sorry, I forgot about this issue. As far as I read, it should work with 1.0.X. I found several references about this issue, and all of them affect only 1.1.X versions: 
- https://github.com/dun/munge/issues/54
- https://bitcoin.stackexchange.com/questions/50125/failing-to-build-bitcoin-core-v0-13-1-on-debian-stretch
- https://github.com/Tau-Coin/taucoin/issues/15

Please make sure your development libraries are also 1.0.X. 
In my case, I built with 1.0.1t with no problems. 
When I run: `grep -i "OPENSSL_VERSION" /usr/include/openssl/opensslv.h `, I get: 
```
# define OPENSSL_VERSION_NUMBER  0x1000114fL
#  define OPENSSL_VERSION_TEXT    "OpenSSL 1.0.1t-fips  3 May 2016"
#  define OPENSSL_VERSION_TEXT    "OpenSSL 1.0.1t  3 May 2016"
# define OPENSSL_VERSION_PTEXT   " part of " OPENSSL_VERSION_TEXT
```
If your OPENSSL_VERSION_NUMBER is less than 0x10100000L, it should work without no change (reference: https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#Backward_compatibility) 

If nothing works for you, you can attempt to correct code by yourselves and re-built. It doesn't look hard. 
Take a look at this example: https://github.com/bitcoinxt/bitcoinxt/pull/209/commits/1f719c0c38c0b80bfef75aeab0a60017bc74fe18 
**Remark**: This example modifies `EVP_MD_CTX` structure, it'd be the same for `EVP_CIPHER_CTX`. I mean in `crypthelper.cpp`, you should do something like: 
``` 
[....] 
EVP_CIPHER_CTX *encryptCtx = EVP_CIPHER_CTX_new(); // set pointer to struct and allocate 

/* Since encryptCtx is already a pointer, you have to remove its "address of " operator (&) 
in any function that uses, such as EVP_CIPHER_CTX_init, EVP_EncryptInit, etc.  */ 

[...]

EVP_CIPHER_CTX_free(encryptCtx); // don't forget to free when no longer needed. 
```
 
Please, let us know any advance. 

Regards.

**Comment by albmed** [comment]
Hi, 

I patched `crypthelper.cpp` and pushed into my own repo. It should work with both openssl 1.0.X and 1.1.X. Please take it from https://github.com/albmed/pokerth/blob/f9a2ebebb45a539df550b0a17d8bf4a95a476559/src/core/common/crypthelper.cpp and try to built it again. 

Please, let us know if it works. I'll push into official PokerTH repo, unless you find any problems. 

Regards.

**Comment by redlance72** [comment]
hi @albmed 
it works 👍   thank you !!!
