### ISSUE TITLE
[FEATURE REQUEST] possibility to ignore a player on the table's chat

### ISSUE THREAD

**Issue by trebmuh** [pokerth/pokerth#365]
_Using 1.1.1 on Debian Stretch here._

I know this is possible to ignore a player on the main window's chat. I'd like to be able to ignore a player as well when playing on a table. A bunch of people are aggressive and insulting there and I'd like to play quietly. If I'm not wrong, the chat functionality is using an IRC backend so it might be possible to use the `/ignore` function there.

A nice addition would be to display on the chat "XXX is ignoring YYY" when the ignored one is pinging (= writing the name of) the ignoring one, hence the others people on the table are aware too.

**Comment by q4z1** [comment]
Hi trebmuth,

it is also possible to ignore players ingame using a right-click on the player avatar followed by a click on "ignore player". It will happen immediately then.

fyi: in-game chat is not controlled/managed by IRC - only the lobby-chat is.

Kind regards.

**Comment by trebmuh** [comment]
> it is also possible to ignore players ingame using a right-click on the player avatar followed by a click on "ignore player". It will happen immediately then.

Oh nice, I didn't noticed that before. Thank you.

> fyi: in-game chat is not controlled/managed by IRC - only the lobby-chat is.

OK, good to know.
