### ISSUE TITLE
This bs isnt working you have no setup instructions i get an error:

### ISSUE THREAD

**Issue by jamieduk** [pokerth/pokerth#366]
./pokerth: No such file or directory

sort it out add a readme to show exactly how to setup¬!

**Comment by albmed** [comment]
Hi @jamieduk, 

Did you try `./pokerth.sh`? I assume you are running PokerTH within the right directory, aren't you? 

If that not work either, can you give us more details? Did you install a release (in that case, which one) or built from source code? 
 
Regards.

**Comment by albmed** [comment]
We didn't get any feedback, so I close this issue.
