### ISSUE TITLE
Straight flush - Ace low

### ISSUE THREAD

**Issue by Statler-Waldorf** [pokerth/pokerth#369]
Lost a hand that (I think) I should have won.

Opponent had a straight 2D,3D,4D,5D,6C.
I had a straight flush AD,2D,3D,4D,5D.

Hand was awarded to opponent.

Is this a bug, or is the Ace-low straight-flush intentionally not recognized?

**Comment by q4z1** [comment]
Hi,

thx for the report.

Can you provide the gamelog pdb file please? You will find it in the Logs section of the client.

Regards.

**Comment by Statler-Waldorf** [comment]
Looks like that log has already cycled out.  Sorry.

**Comment by q4z1** [comment]
Unable to verify hands without log.

**Comment by Statler-Waldorf** [comment]
Sorry.  If it happens again (what are the odds) I'll remember to capture the log.
