### ISSUE TITLE
mysql db connection errors

### ISSUE THREAD

**Issue by mventre** [pokerth/pokerth#370]
When I run the server on Ubuntu 18.04 LTS it starts properly, but there are several mysql db errors that look like this:

`
2019-Aug-02 10:38:35 MSG: Starting PokerTH dedicated server. Availability: IPv6 1, SCTP 1, Dual Stack 1.
2019-Aug-02 10:38:35 ERR: DB connect error: Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'Unknown column 'avatar_hash' in 'field list'.`

I manually created the 'pokerth' database and added tables one by one based on the errors, but this seems like something the compilation process should have handled.

The result is I can't add registered users or allow remote non-guest users to log in.

**Comment by mventre** [comment]
Now I seem to have added all the tables and columns necessary, and I get no error on starting the server, but I can't seem to get my client to connect using a username/password combo. The logfile states things like:

`ERR: Session 2 - Connection closed: asio.misc:2`

**Comment by q4z1** [comment]
Hi mventre,

please take a look here:

https://github.com/pokerth/pokerth/blob/df59bf750f8ce000e600e45fb47cdc5d545c45cf/src/dbofficial/serverdbthread.cpp - line 429 - 431. The password query uses AES_DECRYPT. Make your changes here if you prefer another password hashing mechanism.

Regards.
