### ISSUE TITLE
For internet ranking games, stop increasing blinds at 1600-3200 or 3200-6400.

### ISSUE THREAD

**Issue by Gitoffthelawn** [pokerth/pokerth#371]
When the BB is above 6400, the entire game is largely just bingo.

I suggest, for internet ranking games, stop increasing blinds at 1600-3200 or 3200-6400.

As an "in-between" option, you could increase them to 2500-5000, and stop there.

**Comment by albmed** [comment]
Hi @Gitoffthelawn, 

I think this request should be better addressed to PokerTH forum. In case PokerTH community agrees, we'll change it. 
For now, I close it.
