### ISSUE TITLE
Register fail - mail not sent

### ISSUE THREAD

**Issue by icetronics** [pokerth/pokerth#380]
Hi, when trying to register a new account, I receive an error:
* status: "nok"
* response: "mail not sent"

I tried with 3 different email addresses. Could you please check? Thanks in advance

**Comment by greglepenta** [comment]
Hello,  
I have the same issue

**Comment by q4z1** [comment]
It's working again - moved to another mail delivery service.

Sorry for inconveniences.

**Comment by icetronics** [comment]
Thanks! Unfortunately it still gets stuck at:

> Saving data into database and sending out a validation email ...

but the email does not arrive. Besides, I've used up all my emails :D Would it be possible to remove my accounts I created today? I can send you the addresses in an email. Thank you

**Comment by q4z1** [comment]
Service is blocked again.

Email Validation disabled now - follow these steps:

* register and wait for "mail not sent"
* go to https://www.pokerth.net/component/pthranking/?view=emailval
* enter your username instead of activation key

... that should work.

Sorry - it's a quick & dirty fix.

**Comment by q4z1** [comment]
> Thanks! Unfortunately it still gets stuck at:
> 
> > Saving data into database and sending out a validation email ...
> 
> but the email does not arrive. Besides, I've used up all my emails :D Would it be possible to remove my accounts I created today? I can send you the addresses in an email. Thank you

Deleted all beforee 20:40 CET

**Comment by icetronics** [comment]
Thank you @q4z1 ;) much appreciated
