### ISSUE TITLE
Poker TH crashes Win10

### ISSUE THREAD

**Issue by DanielJones8** [pokerth/pokerth#384]
Hi there,

unfortunately my poker th crashes randomly after serveral minutes (timeout) again and again. I am using a fritz.box (dsl 50.000). I often have the chance to re-join the game, but at the moment the poker th servers are fully occupied - meaining I have no chance to rejoin the table.

Is there a possibility to maybe set some settings at the fritz.box (firewall, allow a certain ip/server etc) to prevent these crashes?

Thanks in regard,
Daniel

**Comment by q4z1** [comment]
Hi Daniel,

it was propably the crowded situation. We've set up a 2nd official server as fallback. I hope it will be better tonight.

There wre also reports about general ISP issues from a few players worldwide - not sure if it was maybe a mix of it.

Kind redards.
