### ISSUE TITLE
Add an option to mute the sound

### ISSUE THREAD

**Issue by MyNameIsTroll** [pokerth/pokerth#385]
Could we have an option to mute the sound? In the menu or an icon on the interface?
I like to listen to music while I play, is it sometimes unpleasant to do so with the sound of the game.

**Comment by q4z1** [comment]
Please check Settings of the pokerth client. There you can completely deactivate sound.

**Comment by MyNameIsTroll** [comment]
Sorry, I didn't see that.
Thank you for your answer.
