### ISSUE TITLE
Ubuntu 18.04 Build Official Server - Compile Error

### ISSUE THREAD

**Issue by github-jeff** [pokerth/pokerth#386]
**Environment Setup:**
sudo apt-get update
sudo apt-get upgrade

sudo apt-get install -y qt5-default libboost-all-dev libcurl4-gnutls-dev libtinyxml-dev libircclient-dev libgsasl7-dev libsqlite3-dev libgcrypt20-dev zlib1g-dev libsdl2-mixer-dev libsqlite3-dev protobuf-compiler libprotobuf-dev libprotoc-dev libmysql++-dev g++-6 gcc-6

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 20
sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
sudo update-alternatives --set cc /usr/bin/gcc
sudo update-alternatives --set c++ /usr/bin/g++

**Git Commands:**
cd /home/ubuntu
git clone https://github.com/pokerth/pokerth.git
cd pokerth
git checkout stable

**Configuration Mods:**
nano pokerth.pro
add
CONFIG += c++11

**Compile Commands:**
qmake CONFIG+="official_server" -spec linux-g++ pokerth.pro
make

**Error:**
serverbanmanager.cpp:(.text._ZN5boost16re_detail_10650116re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10650116re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x174): undefined reference to `boost::re_detail_106501::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
serverbanmanager.cpp:(.text._ZN5boost16re_detail_10650116re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10650116re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x33a): undefined reference to `boost::re_detail_106501::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
collect2: error: ld returned 1 exit status
Makefile.pokerth_server:209: recipe for target 'bin/pokerth_server' failed
make[1]: *** [bin/pokerth_server] Error 1
make[1]: Leaving directory '/home/ubuntu/pokerth'
Makefile:163: recipe for target 'sub-pokerth_server-pro-make_first-ordered' failed
make: *** [sub-pokerth_server-pro-make_first-ordered] Error 2

Pretty sure it's a c++11 / boost error, but not sure how to go about fixing it.

**Comment by q4z1** [comment]
Hi,

I assume that there are two different versions of boost installed. Headerfiles and Libs do not match.

... also please take a look here: https://github.com/pokerth/pokerth/wiki/Building-PokerTH-for-Linux


Regards.

**Comment by q4z1** [comment]
I do  `apt-get build-dep pokerth` on a clean ubuntu 18.04 - installing just 1-3 libs more and that's it.

mysql++-dev for example. But boost and stuff is done with the build-dep install.

**Comment by github-jeff** [comment]
Which source do you use for build-dep?  Clean ubuntu, or at least the aws version, does not come with a pokerth package reference.  Lastly, where is the error log located?  That will certainly help me figure the simple problems.

**Comment by github-jeff** [comment]
This compiled, I think.  There were a quite a few warnings thrown in mysql++, see below for an example.

/usr/include/mysql++/beemutex.h:64:18: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
  BeecryptMutex() throw (MutexFailed);
                  ^~~~~

/usr/include/mysql++/refcounted.h:104:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<T> exception_guard(counted_);

Can these be ignored?

**Comment by q4z1** [comment]
Hi,

you did it so far - deprecation warnings can be ignored, MySQl server is not a must:

It depends on what you want. Now you have a server, where players cann connect and chat - without any login credential verification.

If you want credentials, you will need a database (and a MySql Server) behind it. We did not make the database structure which we are using public though.

But as said ... so far you do have a running server now. You can of course build without the DB - using CONFIG+="" instead of CONFIG+="official_server". That will result in a server without database.

Check ~/.pokerth/config.xml for some customizations (e.g. Port).

Regards.

**Comment by github-jeff** [comment]
Thanks I'll take a look at the config.  All this effort is for an occasional small neighborhood game and that is about it.  I clearly have plenty of compute power over at aws which is not being used if you wanted to setup your non-public database for some of your user base and I can certainly assist in that regards.  Let me know.

**Comment by q4z1** [comment]
Can you give me an email address please - send it to webmaster@pokerth.net
As we do have two servers now - an aws database would be really great.

**Comment by github-jeff** [comment]
Sent a note over, but have not heard back.  Been playing around on the internet games.  The new server side looks like it works pretty well too.

**Comment by q4z1** [comment]
Hi jeff,

thx a lot for your offer. Had a talk with dev-team. There is no urgent need so far. I'd like to poke you when it's urgent.

**Comment by github-jeff** [comment]
No problem, setting this up anyway.  If the need arises, you have my PM.
