### ISSUE TITLE
syntax error on game table URL

### ISSUE THREAD

**Issue by tobbi** [pokerth/pokerth#389]
This is the table I'm playing:
https://www.pokerth.net/component/pthranking/?view=pthranking&layout=gametable&nick1=tobbi&nick2=djavel&nick3=sparkle&nick4=Corkscrew&nick5=ravodin&nick6=dist&nick7=Momo%20Doyle&nick8=bem2&nick9=GaryFSU&nick10=margaux&table=Brasil%2002

Error message:
`syntax error, unexpected '' // 23Diamonds' (T_CONSTANT_ENCAPSED_STRING), expecting ')'`

**Comment by q4z1** [comment]
Hi tobbi,

I cannot reproduce - link opens without error.

But the error message is clear: can you provide a line-number so that I know exactly where to take a look?

Regards

**Comment by tobbi** [comment]
You're right, the issue fixed itself somehow. I'm gonna close this.
