### ISSUE TITLE
Don't store passwords in plain text

### ISSUE THREAD

**Issue by CruseCtrl** [pokerth/pokerth#390]
When I signed up for an account to use PokerTH online, I was sent an account activation email with my password in the body of the email in plain text! This shouldn't be possible, because only password hashes should be stored in your database, not the passwords themselves.

**Comment by q4z1** [comment]
Agree - this is a relict.

But ... it is not about any commercial transaction at all - open source.
The mail is the only situation where a password is sent in cleartext. Rest of it is hashed.

You can change your password after registration/activation if you feel uncomfortable with it.

Regards.
