### ISSUE TITLE
Security issue: missing mysql_real_escape_string

### ISSUE THREAD

**Issue by stensonb** [pokerth/pokerth#391]
While trying to change my password on the webpage, I was directed to a page which states "call to undefined function mysql_real_escape_string()"

I have a screenshot...this _just_ happened (maybe what I see can be correlated with server logs).

My attempted new password had characters notorious for breaking things like this...think bobby drop tables.

Lmk if I can provide more info on this.

**Comment by stensonb** [comment]
Looks like this missing function is preventing _any_ password change.

This, combined with the password _in my confirmation email_ is pretty bad.

**Comment by stensonb** [comment]
https://sv01.siliconvortex.com/pokerth-password-issue.png

I'm trying to change my password from this page: https://www.pokerth.net/community/forum/my-profile

I was presented with this page when attempting to change to several passwords, including those with:

- "complicated" characters ('*', '&', etc)
- _and_ "normal" ansi characters

I have replicated this issue on multiple devices, with multiple browsers.

**Comment by stensonb** [comment]
here are the request headers my browser is using:

Host: www.pokerth.net
User-Agent: Mozilla/5.0 (X11; OpenBSD amd64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: multipart/form-data; boundary=---------------------------32788974673576764983903715394
Content-Length: 5875
Origin: https://www.pokerth.net
Connection: keep-alive
Referer: https://www.pokerth.net/community/forum/my-profile/edit/92876-stensonb
Cookie: __cfduid=db5c8ca2544cda7e0af7150328e63a46c1588795898; 05e679b8f34ab778fc228443c895344a=28fo6nf6s0b9sb4t4gv1lft9up; __gads=ID=2a432b59f15c044b:T=1588795906:S=ALNI_MZm0B8KhuxXZ7_zSa4djXM8wXKI5A; joomla_user_state=logged_in
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache
TE: Trailers

**Comment by q4z1** [comment]
Thx for details.

Joomla caugth this error and displayed it on its own style.

I know where to look now ;-)

**Comment by q4z1** [comment]
Can you please try again? It should work now.

**Comment by stensonb** [comment]
yup, looks good now.  i'm able to change my password without issue.

thanks.
