### ISSUE TITLE
additional flags

### ISSUE THREAD

**Issue by Njet1** [pokerth/pokerth#394]
A user suggested having a Welsh flag.

Beside of Wales there are several autonomous countries and regions like Scotland, Northern Ireland, Greenland, Faroe Islands and many more but it's hard to say which of those could get asked for. Scotland and Northern Ireland have a relatively high population and are within 'PokerTH reach' so that could be worth a try.

**Comment by q4z1** [comment]
Hi Njet,

can you provide flag graphics - minimum 96 px width.

Thx a lot for your effort!

We talk about how many flags then?

Regards

**Comment by Njet1** [comment]
I would go for Wales and Scotland only. Northern Ireland's official flag is the union jack though there are other flags they use like the attached one. I think it would be easiest to keep it like now until someone from Northern Ireland actually asks for a flag.

![Northern Ireland](https://user-images.githubusercontent.com/65250400/81835542-e9670380-9531-11ea-8dbd-7eaff5d3bb1b.png)
![Scotland](https://user-images.githubusercontent.com/65250400/81835546-e9ff9a00-9531-11ea-9953-b49ba06ee68a.png)
![Wales](https://user-images.githubusercontent.com/65250400/81835548-ea983080-9531-11ea-8a46-cb5ac350cad6.png)




The attached flags are taken from wikimedia and public domain.

**Comment by Njet1** [comment]
s3..... asked for putting up a request for this flag. It's not a flag of a particular country but of the Berber people.

https://en.wikipedia.org/wiki/Berber_flag

**Comment by thomasboehm** [comment]
Welsh, Scottish, English and European flag exist in the profile settings.
