### ISSUE TITLE
spectate

### ISSUE THREAD

**Issue by SergeyShorin** [pokerth/pokerth#409]
Hello!
I often try "spectate", but this tool not work.
![Снимок экрана в 2020-11-05 12-11-50](https://user-images.githubusercontent.com/10895820/98204424-36b3b300-1f60-11eb-992b-77746f5072a4.png)

**Comment by q4z1** [comment]
Hi Sergey,

this is the common session timeout - like 15 minutes. If you do no interact with the browser tab/window at all, you get disconnected after that period.

Kind regards.

**Comment by SergeyShorin** [comment]
In general, I have never been able to connect.
when i click "login" how should i interact with the browser / tab with the modal-window open?
in a minute the above error pops up

**Comment by q4z1** [comment]
Ah. Guest login online.



SergeyShorin <notifications@github.com> schrieb am Fr., 6. Nov. 2020, 23:39:

**Comment by SergeyShorin** [comment]
yes! only guest login work.
may be better lock "login/password" field? 
...and unlock they in future (when they are start working correct)

**Comment by q4z1** [comment]
Sounds offending. But yeah.... 4 new players the mask is irritating. You could have checked forum abt it.

**Comment by SergeyShorin** [comment]
oh! sorry! i not desired say some offending. sorry!

**Comment by q4z1** [comment]
Please check pokerth-live project. Should be easy to fix. I created an issue.
