### ISSUE TITLE
Unavailable card deck link

### ISSUE THREAD

**Issue by AlekseyLobanov** [pokerth/pokerth#412]
Hello.
I think that some of links on official page with [card decks](https://www.pokerth.net/media2/styles-gallery/card-deck/) are broken.

For example,  _Nobus 4-color full color card deck v2_, [link](https://sourceforge.net/projects/rj10328.u/files/PokerTH_Custom_Cards/Full_4_color_card_deck_by_Nobus1967_modified.zip/download)

**Comment by andy5995** [comment]
It looks like the [link to the card decks](https://www.pokerth.net/app.php/gallery) has changed since this issue was opened and the *Nobus 4-color full color card deck v2* has been removed.
