### ISSUE TITLE
disaster recovery plan n/a

### ISSUE THREAD

**Issue by FiSHYsolutions** [pokerth/pokerth#419]
![fail](https://user-images.githubusercontent.com/222112/111014952-9b679a00-83a6-11eb-96ad-751f73e260a6.png)
![dr](https://user-images.githubusercontent.com/222112/111014970-b803d200-83a6-11eb-8ad8-a47ea112d77b.png)

SNAFU happened 3 days ago, the pokerth-website is still offline.
there is obviously a lack of DR...

> Backup situation as follows: no external backup, OVH backup storage is propably burnt, too.

**Comment by q4z1** [comment]
no relevance here in the dev section.
