### ISSUE TITLE
Cant' log in

### ISSUE THREAD

**Issue by ql0wn4** [pokerth/pokerth#426]
The software (windows) gives invalid password error but the password is correct

**Comment by thomasboehm** [comment]
Please reset your password here https://www.pokerth.net/app.php/user/forgot_password. Make sure that nothing is blocking JavaScript, since this is required to run in order to create the gaming account.

**Comment by Lorand888** [comment]
My question is, is the Texas Hold'em game functional or is it still under development?

Best regards,
Lorand

**Comment by thomasboehm** [comment]
It's functional. If you have a problem, post it on the forum https://www.pokerth.net
