### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by samo-nz** [pokerth/pokerth#436]
I understand this is not the correct place to report registration issues BUT there is no way to contact anyone through the website, no discord invite, no email addresses, no IRC.

I failed the robot check as the characters are almost impossible to understand, after which the website informed me to contact a forum admin, which I cannot do as I'm not able to log in, the forum admin page has been disabled also.

Can someone please help me create an account?

**Comment by q4z1** [comment]
Hi,

obviously the discord widget is broken again - we already fixed it a few weeks ago. Thank you for info.

Beside of that, the website contains an imprint link in the footer with an email address: https://www.pokerth.net/app.php/imprint 

Please send an email to webmaster (at) pokerth.net - I will assist you then.
