### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [pokerth/pokerth#437]
Dear @pokerth team, @lotodore, @floty, @doitux, @q4z1, @albmed,

The current version 1.1.2 (2018-05-18 / tag: 2017-08-16 / SF: 2017-10-31) is very old, I think it is time to update?
- https://github.com/pokerth/pokerth/releases
- https://github.com/pokerth/pokerth/tags
- https://sourceforge.net/projects/pokerth/files/pokerth/1.1.2/

Thanks in advance.

**Comment by Neustradamus** [comment]
@q4z1: No answer, it has not been solved, can you reopen?

**Comment by q4z1** [comment]
It's repetitive - please check pokerth.net: you can just now read information about a possible new version directly on Start page.

**Comment by q4z1** [comment]
Besides it feels a bit like GitHub spamming to me, creating like 5 issues in minutes in different repos with really minor things. It's not really contributive.

**Comment by Neustradamus** [comment]
@q4z1: 4 issues are different.

Here, it is to have a new release build after current version from 2017 (We are in 2025, 8 years this year).

After, it is to update Sourceforge project to be in relation with GitHub:
- https://github.com/pokerth/pokerth/issues/438

After, it is to have good repositories at good place, currently there are two bad forks here:
- https://github.com/pokerth/pokerth_monthlycup -> https://github.com/q4z1/pokerth_monthlycup/issues/1
- https://github.com/pokerth/bbc_wec_site -> https://github.com/q4z1/bbc_wec_site/issues/77

**Comment by q4z1** [comment]
I'd be glad, if you can wait until mid of January 2025. I will have more time then to get into details with you.

**Comment by Neustradamus** [comment]
@q4z1: I contact you again to know when you will create the new version?

Can you reopen this unsolved ticket?

Thanks in advance.

**Comment by q4z1** [comment]
If there will be a date - you will propably be one of the first to be notified. Thank you for your patience.

**Comment by Neustradamus** [comment]
Dear @pokerth team, @lotodore, @floty, @doitux, @q4z1, @albmed,

I do a comeback to you more one year after my original ticket.

When do you release a new version?

Thanks in advance.

**Comment by q4z1** [comment]
Dear @Neustradamus: do you want to annoy me? There is no more lotodore, floty or doitux or albmed in dev team.
Beside: did you check latest news in PokerTH forum, or the newest issue here?
The new release on github is only a few bugfixes away from official publishing.
Save your energy and my time and read!
